### ISSUE TITLE
grape bunch grouping

### ISSUE THREAD

**Issue by andreaceruti** [thsant/wgisd#8]
Looking at the dataset with your notebook WGISD.ipynb I have noted that sometimes the same grape bunch mask is splitted in 2 different parts. For example I have inserted in train_masked.txt the image "CDY_2015" in order to visualize it and the result is the one in the screenshot you see. You can see on the left that instead of one single mask we have 2 masks (purple and green adjacent masks) and also the grape bunch below is separated in 2 parts.
<img src="https://user-images.githubusercontent.com/44469014/141489864-cc11cc98-d94a-4c7c-8762-e58662b35fea.png" height="500">

So I was wondering if this is a design choice since the image was used for testing and not for training or if It regards something that I am not aware of.

**Comment by thsant** [comment]
Dear @andreaceruti, if you look for the **peduncles**, you will see the green and purple bunches came from _different peduncles_, so they are _different brunches_. However, annotation is error-prone and WGISD is not free of errors, most of them caused by single view of complex 3-D objects with overlap. But this is not the case in the example above: a close look will reveal that the green and the purple masks are really from different bunches.
